### PR TITLE
don't break while generating tokens for names with non-ascii characters

### PR DESCRIPTION
**Pull request by davisagli**
(which could come from user input in the creator field,
see https://github.com/plone/plone.app.widgets/issues/120)

### CODE REVIEW

**Comment by davisagli** [comment]
Tests: http://jenkins.plone.org/job/pull-request-5.0/600/

**Comment by davisagli** [comment]
Trying again: http://jenkins.plone.org/job/pull-request-5.0/601/

**Comment by davisagli** [comment]
Fixed test, trying again: http://jenkins.plone.org/job/pull-request-5.0/603/

**Comment by davisagli** [comment]
Passing

**Comment by jensens** [comment]
fetching fullname can be expensive, did you try this with many users?

**Comment by davisagli** [comment]
I didn't change that part, I just made it encode the value to create the token when it needs to, and reduced code duplication.

**Comment by thet** [comment]
looks good, only i'm wondering why you are using the unicode_escape encoding for the token and not quoted-printable encoding, like for plone.app.vocabularies.catalog KeywordsVocabulary?

**Comment by jensens** [comment]
I'd just merge, i think which encoding is used here does not make a big difference. I'd have used quoted-printable too, since its an encoding which can be used outside python world too easily.
But we may want to change this in another PR if this is a thing.

**Comment by thet** [comment]
+1

**Comment by davisagli** [comment]
I used unicode_escape out of habit...I wasn't really familiar with quoted-printable, but it looks like a good choice too.

**Pull request merged**
