### PR TITLE
Add Creators vocabulary

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Nice to use this for the Creator query in a Collection, instead of the Users vocabulary.

Would be nice to have tests for this, which I tried. Current similar tests mock all kinds of things, which failed for me. Other tests that actually have a portal don't have any content and only have Discussion Item and TempFolder as content types, and I couldn't even create a Discussion Item. Maybe some other base class or test fixture and all would be fine, but it has to work on Plone 4.3 and 5.0, so I gave up.

Showing fullnames would be nice.

### CODE REVIEW

**Comment by jensens** [comment]
- documentation in README is missing
- changelog entry is missing.

ad tests: isnt it enough to add some fake creators to the index instead of having the full stack work?

**Comment by jensens** [comment]
@mauritsvanrees amy update on this one?

**Comment by mauritsvanrees** [comment]
No. This change was a side track from a side track from a side track, so it is not high up my list.
I'll probably get to it eventually. But if someone wants to finish the work on this branch or start a new branch, I am happy with that too.

**Comment by jensens** [comment]
There was no activity on this for a while. I close this request for now. If you plan to work further on this please reopen and go on.

**Pull request closed without merging**
