### PR TITLE
part of Plip 1342: portal actions controlpanel

### PR DESCRIPTION
**Pull request by ebrehault**
See https://github.com/plone/Products.CMFPlone/issues/1342
Related to https://github.com/plone/Products.CMFPlone/pull/1385

### CODE REVIEW

**Comment by jensens** [comment]
may you please document the new vocabularies short in README.rst like the others are?

**Comment by ebrehault** [comment]
done

**Comment by gforcada** [comment]
Do we need to mark master in a special way to know that this is **only** meant for Plone 5.1?

**Comment by gforcada** [comment]
@plone/framework-team @plone/release-team ^

**Comment by jensens** [comment]
true, we may want a 5.1 branch on buildout.coredev? from what I get from @esteele yesterday at FWT meeting all releases for 5.0.3 are done and all further development is for a 5.1

**Comment by davisagli** [comment]
If you're introducing a change that is not meant for Plone 5.0, you should:
1. Create a branch at the commit before the change is added. This branch is typically named after the current version, i.e. if package version is 2.0.1, the branch would be called 2.0.x. In the future bugfixes can be added on this branch, while new features will be added on master.
2. Update coredev's 5.0 branch to use the maintenance branch of the package instead of master.
3. On master, increment the minor version number to indicate new features.

**Comment by davisagli** [comment]
And, of course, create a 5.1 branch of coredev if one doesn't exist yet, which should continue to use master of this package.

**Comment by jensens** [comment]
indeed. its on my todo list for this week if nobody else is faster

**Comment by jensens** [comment]
@davisagli this is just another vocabulary so it has zero impact on 503

**Comment by davisagli** [comment]
True, so I guess a new branch isn't necessary then.

**Pull request merged**
