### PR TITLE
Remove zope.formlib dependency

### PR DESCRIPTION
**Pull request by gforcada**
Fixes https://github.com/plone/plone.app.vocabularies/issues/38

### CODE REVIEW

**Comment by jensens** [comment]
Since this only affect User and Group vocabularies I guess this was in use for the controlpanel in 4.3 and is no longer used anywhere and so save to remove.

**Comment by gforcada** [comment]
@jensens is that enough to mark it as deprecated?

**Comment by jensens** [comment]
Yes, looks good this way.

**Comment by gforcada** [comment]
Random tests fail on 5.1 ... :-/

**Comment by jensens** [comment]
In 5.1 now too? Annoying.

**Comment by gforcada** [comment]
Finally green!

I merge it before it breaks again :-)

**Pull request merged**
