### PR TITLE
Restrict catalog vocabulary to context navigation root unless path is specified.

### PR DESCRIPTION
**Pull request by alecpm**
[Build Status](http://jenkins.plone.org/job/pull-request-5.0/926/)

### CODE REVIEW

**Comment by alecpm** [comment]
Relates to and requires plone/plone.app.z3cform#41 plone/plone.app.content#72 plone/plone.app.dexterity#206 plone/plone.app.multilingual#210 plone/Products.Archetypes#52

**Comment by alecpm** [comment]
Also related to (merged) plone/plone.app.widgets#128 plone/mockup#622

**Comment by jensens** [comment]
combined test with all above open PRs branches in checkout http://jenkins.plone.org/job/pull-request-5.0/943/

**Comment by jensens** [comment]
merged, lets watch jenkins - but should work.

**Comment by alecpm** [comment]
Thanks Jens!  I made two earlier Jenkins runs for these pull requests (http://jenkins.plone.org/job/pull-request-5.0/926/ http://jenkins.plone.org/job/pull-request-5.0/928/) so I don't anticipate any issues.

**Pull request merged**
