### PR TITLE
Add images scales vocabulary to master

### PR DESCRIPTION
**Pull request by bsuttor**
As demanded https://github.com/plone/plone.app.vocabularies/pull/29

I make same PR on 2.1.x and on master branch

### CODE REVIEW

**Comment by thet** [comment]
Thanks! That's something I wanted since quite some time.

**Comment by thet** [comment]
before this is getting merged, the commits should be squashed.
/cc @bsuttor

**Comment by jensens** [comment]
all green, all fine and a good one to try the new squash commit option :) so let me do it.

**Comment by jensens** [comment]
nice new feature github! b5f4c8c18e8adebca0c9c27c585255a3018e7284

**Pull request merged**
