### PR TITLE
Remove usage of `portal_properties`.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
In `getForbiddenContentTypes` we used to check `portal_properties.site_properties.forbidden_contenttypes`.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Review by jensens — APPROVED** [review]

**Comment by jensens** [comment]
If we want to remove the method in future, additional a deprecation message could be handy.

**Comment by mauritsvanrees** [comment]
> If we want to remove the method in future, additional a deprecation message could be handy.

Done.  Marked for removal in Plone 7.

@jenkins-plone-org please run jobs

**Pull request merged**
